<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>git-rebase-todo</string>
	</array>
	<key>name</key>
	<string>GitRebase</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.git-commit-message</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.number-sign.git-commit-message</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.rebase.commands</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(Commands:)$</string>
					<key>name</key>
					<string>comment.line.rebase.commands</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pick</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.pick</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(p),\s+?(pick)\s+?=\s+?([^\n]*)$</string>
					<key>name</key>
					<string>comment.line.pick</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.reword</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.reword</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(r),\s+?(reword)\s+?=\s+?([^\n]*)$</string>
					<key>name</key>
					<string>comment.line.reword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.edit</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.edit</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(e),\s+?(edit)\s+?=\s+?([^\n]*)$</string>
					<key>name</key>
					<string>comment.line.edit</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.squash</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.squash</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(s),\s+?(squash)\s+?=\s+?([^\n]*)$</string>
					<key>name</key>
					<string>comment.line.squash</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.fixup</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.fixup</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(f),\s+?(fixup)\s+?=\s+?([^\n]*)$</string>
					<key>name</key>
					<string>comment.line.fixup</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.exec</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.exec</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(x),\s+?(exec)\s+?=\s+?([^\n]*)$</string>
					<key>name</key>
					<string>comment.line.exec</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?!p|pick|r|reword|e|edit|s|squash|f|fixup|x|exec|\#|\s*?$)\s*?[^\n]*$</string>
			<key>name</key>
			<string>invalid.illegal.rebase</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=p|pick|r|reword|e|edit|s|squash|f|fixup|x|exec)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.paragraph.rebase</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pick</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.pick</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.pick</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(p|pick)\s+?(.{7})\s+?(.*)</string>
					<key>name</key>
					<string>pick</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.reword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.reword</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.reword</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(r|reword)\s+?(.{7})\s+?([^\n]*)</string>
					<key>name</key>
					<string>reword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.edit</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.edit</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.edit</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(e|edit)\s+?(.{7})\s+?([^\n]*)</string>
					<key>name</key>
					<string>edit</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.squash</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.squash</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.squash</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(s|squash)\s+?(.{7})\s+?([^\n]*)</string>
					<key>name</key>
					<string>squash</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.fixup</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.fixup</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.fixup</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(f|fixup)\s+?(.{7})\s+?([^\n]*)</string>
					<key>name</key>
					<string>fixup</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.exec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.exec</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(x|exec)\s+?([^\n]*)</string>
					<key>name</key>
					<string>exec</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.git.rebase</string>
	<key>uuid</key>
	<string>99705a2d-c1fc-466e-bf17-20733909bf52</string>
</dict>
</plist>
